### ISSUE TITLE
Replace scrolling ASCII-art interface with a nice ncurses (or similar) environment

### ISSUE THREAD

**Issue by pahp** [pahp/wormwood#1]
The scrolling ascii interface is clunky and I think makes it hard to fully understand what is being displayed. It would be much better if it used a GUI-like interface supported by ncurses: https://en.wikipedia.org/wiki/Ncurses

I suggest that we figure out how to implement something similar to what is there using ncurses and/or meet to discuss how a better ncurses-based design for the interface.

**Comment by ZachyCatGames** [comment]
Fixed by https://github.com/pahp/wormwood/pull/13
