### ISSUE TITLE
authenticating as oper needs no password (bug, or *feature*?)

### ISSUE THREAD

**Issue by pahp** [pahp/wormwood#4]
The instructions say that authenticating as `oper` requires the password `HomerSimpson`, but it doesn't need a password.

This is a bug, but maybe we should keep it as an "intentional" flaw. It's kind of fun for people to find accidentally. Thoughts?

**Comment by pahp** [comment]
Update: 

I think the user should be able to get into `oper` mode without the right password, but should not get into `super` mode without the password.

Up to you whether an empty password "works" for `oper` or is rejected.

**Comment by ZachyCatGames** [comment]
It's A Feature™
